### ISSUE TITLE
Make fonts in Apple music Fullscreen be able to change fonts due to international languages font.

### ISSUE THREAD

**Issue by Loneliplayer** [WXRIW/Lyricify-App#216]
Fonts in apple music lyrics Fullscreen is (maybe) using a default windows font when the lyrics is international making the appearance looks funny. My suggestions are
1. Let user custom with their own font
2. Add more font family to the app by default
3. Bind a font with the language pack

**Comment by WXRIW** [comment]
Which language are you talking about? Btw can you make some screenshots so I can understand your issue more precisely.

**Comment by Loneliplayer** [comment]
Thai and here's a screenshot comparing the one with the lyricify lyrics and the one with the apple music
![Lyricify (already switch the font family)](https://github.com/WXRIW/Lyricify-App/assets/97138950/09c43a8c-142c-4a0b-a5b2-67250d44b98f)
![Apple Music (No options to switch)](https://github.com/WXRIW/Lyricify-App/assets/97138950/ecd4eb6a-b9ab-49c9-accf-b2097a817047)

**Comment by WXRIW** [comment]
Right now there's no way to change fonts in Apple Music Lyrics due to some reasons. I found all customized fonts is not working correctly in this mode while I was debugging. So changing fonts in Apple Music Lyrics is not coming out until I figure out how to make customized fonts work properly. And there's no ETA on this function.
FYI, Apple Music Lyrics mode are using SF Pro Display and PingFang SC as default font.

**Comment by Loneliplayer** [comment]
Thanks for the response! I'm looking forward to see this feature coming out! :D

**Comment by WXRIW** [comment]
I will close this issue as completed now and let you know that custom fonts in Apple Music Lyrics and Dynamic Lyrics Island is coming soon.
We are expecting it to be released in Lyricify 4.3, but might not be in the first release of Lyricify 4.3 (Lyricify 4.3.0). But I am sure it's coming very soon.
Anyway, thanks for your support and patience!
