### ISSUE TITLE
Make a word-to-word translation support and Apple Music Animated Album for Apple Music Lyrics interface(if possible).

### ISSUE THREAD

**Issue by ItzAsyran** [WXRIW/Lyricify-App#300]
It would be nice to have a setting where you can turn on word-to-word translation. It's not really that useful I think but it'll look cool.

For the Apple Music Animated Album, I found one repo that allows you to pull the cover art from Apple primarily animated one.
https://github.com/bunnykek/Fetcher
The setting can be toggled on or off but I think for "Best Quality" settings, this should be turned on. It'll look nice on the Apple Music Lyrics Interface.

once again, this is only a suggestion to make the app look more great.
and also please add translation for in-app tools for syllables creator, i want to use it but it's in chinese

EDIT: I forgot to ask if it's possible to fix the arabic syllables? it look so messed up right now. it should be right to left
<img width="331" alt="Screenshot 2024-03-29 013319" src="https://github.com/WXRIW/Lyricify-App/assets/78186421/6167b8a3-3d52-4657-bdb9-35cca3b39564">

**Comment by WXRIW** [comment]
Word-by-word translation looks great but it is nearly impossible to make on technical level. So it cannot be achieved in Lyricify.
Live Album Cover is made available in the first release of Lyricify 4. This feature is a special feature for specific albums, like [this one](https://open.spotify.com/album/0SrskI3mHcu5MzKeZNv2f6?si=cxwUsE4oRj6A8FSMiryizA). Due to the special nature of this feature, I will only enable it for specific albums and will not accept new albums submitted by users.
The syllable tools' will be translated for localization in future versions, thanks for your advice! BTW, we suggest you to use other syllable lyrics creators since the build-in one is not user friendly. It is suggested to use [this tool](https://github.com/WXRIW/Lyricify-App/blob/main/docs/Lyricify%204/Lyrics.md#%E5%88%B6%E4%BD%9C%E5%B7%A5%E5%85%B7-2) instead.
For the arabic (and all other RTL languages) syllable issue, because it is too niche and the cost of optimization is too high, we currently have no plans to optimize it.

**Comment by WXRIW** [comment]
Due to no reply received for a long time, this issue is going to be closed.
