### ISSUE TITLE
授权回调失败了，软件没反应。

### ISSUE THREAD

**Issue by Fihven** [WXRIW/Lyricify-App#364]
网页授权成功了，软件没有反应。过程中没有使用代理。
![屏幕截图 2024-06-14 133556](https://github.com/WXRIW/Lyricify-App/assets/75319612/ec3c5266-97ad-44ab-ac6a-708c8b64dd91)
![image](https://github.com/WXRIW/Lyricify-App/assets/75319612/0eab517b-487d-489c-913b-f3ef1daf417e)

尝试了手动复制回调链接：http://localhost:766/callback?code=AQDhJhcHP5t2tWU1R6kSwkekYQ4mQ-exo1uu-gLICE_vaE7lcs4L5w9PINrsFS8aNHWpxiIrooFY-8W4j_Nkc2i_epVmgxfGN2zF40LzvZBj48UmpqDDJRttXtQIfSyyC9cf5ok5GTCyyJNdFn4U58p9Qkj7Pi67iIjc-Hi8hq_FB1hfA9FvCr-EiwCbgnlcoJWtflkh_95jnYpuP4jNcZoz6mHE3pdbp1Uxvgh4doyZgaJJxIiDAEtLyWyrBqf1Ij2RbqjyG6CWn8nX_k1uaYLVvKjwjbG9qIpU8mZdRkMGEi1cwdLqsAFIH-Rijldev4bRjJPjiZ-2CULA5SiBeKxxGA8ciC22XV4d9B04ZXo8aQv4Y4xr14KaPbXyxHNDglI94t1Nb39oqwbb4pXuvoA-vDRvpEDjoJ7b3JfJETjmUdygpKZGJckkNMSJ17Xv3Md7usudBMrgzARpmBTWfITLwxh3_hgrxILbXZ_ND9u3TVPtWWk2mdjv6d1wG3Z3SpK2tZis5nA3Yx7CXQpxXclB635PUn09U11ckwEpzi5vdjvg5K6cosKuOj1Cx8r3_PLNml6GsNMF_PFAXqVKNWfoRnsDax3itY4E7kCfwLRJAL4-fgFlWrWcubjMsS5zajQ-_1YeuZhl90YhepvL_qWoOparmkfByLIDHbXfc6RhTR72TAC-GZ3OuzvroeattiePbC0jw9TXmmWTaF5Jn8io1A 
失败。

**Comment by WXRIW** [comment]
手动授权输入后提示什么。

**Comment by Fihven** [comment]
我靠这么快，你们真负责，显示SSL connetction 无法建立。我正准备重启一下软件试试。

**Comment by WXRIW** [comment]
尝试开启代理 再重新打开软件授权

**Comment by Fihven** [comment]
可以了
![image](https://github.com/WXRIW/Lyricify-App/assets/75319612/1d3de36e-45ba-4ada-9bb7-dab2a501295f)
暴赞！

**Comment by WXRIW** [comment]
应该就是非代理时 国内环境无法访问 Spotify 授权导致的。

**Comment by a2king** [comment]
2024-07-01T17:13:47.3758552+08:00 [Error] System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The SSL connection could not be established, see inner exception.)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at SpotifyAPI.Web.Http.NetHttpClient.DoRequest(IRequest request, CancellationToken cancel)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request, CancellationToken cancel)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request, CancellationToken cancel)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers, CancellationToken cancel)
   at Lyricify_for_Spotify.Windows.WelcomeWindow.vgXfTY9C5N(Object  , AuthorizationCodeResponse  )
   --- End of inner exception stack trace ---
2024-07-01T17:14:26.5723245+08:00 [Error] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
2024-07-01T17:14:33.7825264+08:00 [Error] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
我加了代理还是报错

**Comment by WXRIW** [comment]
> 2024-07-01T17:13:47.3758552+08:00 [Error] System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The SSL connection could not be established, see inner exception.) ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception) at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions) at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) at SpotifyAPI.Web.Http.NetHttpClient.DoRequest(IRequest request, CancellationToken cancel) at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request, CancellationToken cancel) at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request, CancellationToken cancel) at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers, CancellationToken cancel) at Lyricify_for_Spotify.Windows.WelcomeWindow.vgXfTY9C5N(Object , AuthorizationCodeResponse ) --- End of inner exception stack trace --- 2024-07-01T17:14:26.5723245+08:00 [Error] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. 2024-07-01T17:14:33.7825264+08:00 [Error] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. 我加了代理还是报错

看了一下你提供的日志，提示无法建立 SSL 连接，说明就是你的网络问题，请尝试更换网络，或代理节点。

**Comment by a2king** [comment]
> > 2024-07-01T17:13:47.3758552+08:00 [Error] System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The SSL connection could not be established, see inner exception.) ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception) at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions) at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) at SpotifyAPI.Web.Http.NetHttpClient.DoRequest(IRequest request, CancellationToken cancel) at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request, CancellationToken cancel) at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request, CancellationToken cancel) at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers, CancellationToken cancel) at Lyricify_for_Spotify.Windows.WelcomeWindow.vgXfTY9C5N(Object , AuthorizationCodeResponse ) --- End of inner exception stack trace --- 2024-07-01T17:14:26.5723245+08:00 [Error] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. 2024-07-01T17:14:33.7825264+08:00 [Error] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. 我加了代理还是报错
> 
> 看了一下你提供的日志，提示无法建立 SSL 连接，说明就是你的网络问题，请尝试更换网络，或代理节点。

当前节点 我试过spotify 重新登录都是没有问题的诶

**Comment by WXRIW** [comment]
@a2king 尝试修复你的网络，日志显示你遇到的这个问题确实不是 Lyricify 的问题。

**Comment by a2king** [comment]
> @a2king 尝试修复你的网络，日志显示你遇到的这个问题确实不是 Lyricify 的问题。

好的好的，感谢，我排查一下我的网络先

**Comment by a2king** [comment]
> @a2king 尝试修复你的网络，日志显示你遇到的这个问题确实不是 Lyricify 的问题。

您好，我今天调试的时候是本地我766的服务没有成功启动，导致回调失败，请问这个能有什么方式查看日志，
![image](https://github.com/WXRIW/Lyricify-App/assets/35003367/2bb5896d-48d2-42eb-a4a3-82f51323ae63)

**Comment by WXRIW** [comment]
> > @a2king 尝试修复你的网络，日志显示你遇到的这个问题确实不是 Lyricify 的问题。
> 
> 
> 
> 您好，我今天调试的时候是本地我766的服务没有成功启动，导致回调失败，请问这个能有什么方式查看日志，
> 
> ![image](https://github.com/WXRIW/Lyricify-App/assets/35003367/2bb5896d-48d2-42eb-a4a3-82f51323ae63)
> 
> 

这种情况下可以直接手动授权。点击左下角的遇到了问题，然后按提示操作即可。
