### ISSUE TITLE
Ability to specify primary and backup lyrics provider

### ISSUE THREAD

**Issue by rjt-rockx** [WXRIW/Lyricify-App#368]
I want to be able to choose my primary and secondary lyrics provider, because certain songs have wrong lyrics or wrong timing in QQ Lyrics and Netease but correct lyrics in Musixmatch. 
I couldn't find an option to disable QQ and Netease entirely as well, it'd be nice to have that option too.

**Comment by WXRIW** [comment]
Lyricify uses Musixmatch as backup plan, which means Musixmatch is only available when QQ Music and NetEase Cloud Music have no lyrics. If the automatic search finds lyrics from them (even it's wrong), Lyricify will use them instead of Musixmatch. 

Musixmatch is unstable, so we cannot use it as source at any level except the last backup plan level.

**Comment by WXRIW** [comment]
You can search manually on QQ Music and NetEase Cloud Music app, and import them into Lyricify. Lyricify's auto search isn't always correct, so a manual search is needed.
If both QQ Music and NetEase Cloud Music don't have the corresponding lyrics, you can manually upload the correct lyrics into Lyricify Lyrics Vault whether from other sources like Spotify or Apple Music, or made by yourself.

**Comment by rjt-rockx** [comment]
Got it, thanks!

It would be nice if Musixmatch was more reliable, even their official desktop app was really buggy.

**Comment by WXRIW** [comment]
Musixmatch returns 401 or 403 every often at a random time. So it's really unstable.
