### ISSUE TITLE
Open on startup

### ISSUE THREAD

**Issue by rjt-rockx** [WXRIW/Lyricify-App#371]
It would be nice if Lyricify could automatically open on logging into Windows and show the previously selected view, so that I don't have to manually open it and open Desktop lyrics each time.

**Comment by WXRIW** [comment]
We are not planning on this feature cause the experience is not good enough since when Lyricify needs a stable Internet connection to login but at OS startup, the network might not be initiated until minutes later. So Lyricify has a chance to close due to network issue. So we are not making this feature inside Lyricify.
If you do want Lyricify to start with your PC, we have the instructions for setting up Lyricify startup at login manually. The guide are in Chinese, use a translator if you need. Thanks for your feedback.

**Comment by rjt-rockx** [comment]
Will it automatically open the lyrics when opening on startup through the shortcut?

**Comment by WXRIW** [comment]
Desktop Lyrics and Dynamic Lyrics Island will automatically open.
